swagger: '2.0'

info:
  description: |
    This document describes Passbolt Backend REST APIs. They work over HTTPS so they are language/framework agnostic. Clients can consume them in their language of choice using the HTTPS protocol.
  version: "2.7.1"
  title: "Passbolt API Reference"
  termsOfService: "https://www.passbolt.com/terms"
  contact:
    email: "contact@passbolt.com"
  license:
    name: "AGPL-3.0"
    url: "http://www.gnu.org/licenses/agpl-3.0.html"
host: "api.passbolt.com"
basePath: "/"
tags:
- name: "Auth"
  description: Authentication endpoints
- name: "Resource"
  description: |
    Passwords are internally known as `Resources` and are represented as one object containing the `name`, `username`, the actual `password`, the `URL` amongst other fields. The API allows you to create, delete, and update your passwords. You can retrieve individual passwords as well as a list of all your passwords."
- name: "User"
  description: |
    Users are usually people interacting with your account. One `User` object represent one person with their `Profile`, `Avatar` etc.
    
- name: "Group"
  description: Group of users
schemes:
- "https"
paths:
  "/auth/verify.json":
    get:
      summary: "Fetches server's identity for verification"
      description: "Returns server's public key with it's fingerprint. This is to be verified against the saved server identity."
      
      tags:
      - "Auth"
  "/auth/login.json":
    post:
      summary: Logs a user in
      description: |
        The same URL works for two login steps. The server recognises the step from the request payload and headers.
        
        Step 1. Encrypts a random string using server's public key and send to the server as request body in `server_verify_token`
        
        Step 2. After verification, the server responds back with a random token encrypted using client's public key in the header called `X-GPGAuth-User-Auth-Token`. 
        
        Step 3. Client then decrypts and sends the decrypted text in the request body in `user_token_result`.
        
        Step 4. Finally, the server verifies if the decrypted `user_token_result` matches with the original text and is still valid. Upon verification the server creates and returns "authenticated" cookies that can be used to make further requests.
        
        To know more about Passbolt's authentication. Please visit https://help.passbolt.com/tech/auth
      tags:
      - "Auth"
  "/resources.json":
    get:
      description: Returns a list of your passwords. The passwords are returned sorted alphabetically by their name.
      summary: List all Passwords
      operationId: "getPasswords"
      tags: 
      - "Resource"
      security:
      - passbolt_auth:
        - "read:resource"
    post:
      operationId: "createPassword"
      tags: 
      - "Resource"
      summary: Creates a new passowrd.
      description: Creates a new password.
      security:
      - passbolt_auth:
        - "write:resource"
  
  "/resources/{resourceId}.json":  
    get:
      operationId: "getPassword"
      tags: 
      - "Resource"
      summary: "Find password by ID"
      description: "Returns a single password"
      security:
      - passbolt_auth:
        - "write:resource"
    put:
      tags: 
      - "Resource"
      summary: "Update an existing password"
      description: |
        Updates the specified password by setting the values of the parameters passed. Any parameters not provided will be left unchanged.  
          
          This request accepts mostly the same arguments as the `Password` creation call.
      operationId: "updatePassword"
      security:
      - passbolt_auth:
        - "write:resource"
        - "read:resource"
    delete:
      operationId: "deletePassword"
      tags: 
      - "Resource"
      summary: "Deletes a password"
      description: |
        Deletes the password and also drops all the associated permissions.
      security:
        - passbolt_auth:
          - "read:resource"
          
  "/users.json":
    get:
      description: Returns a list of your users. The users are returned sorted alphabetically by their name.
      summary: List all users
      operationId: "getUsers"
      tags: 
      - "User"
      security:
      - passbolt_auth:
        - "read:user"
    
    post:
      operationId: "createUser"
      tags: 
      - "User"
      summary: Creates a new user.
      description: Creates a new user.
      security:
      - passbolt_auth:
        - "write:user"
    
  "/users/{userId}.json":  
    get:
      operationId: "getUser"
      tags: 
      - "User"
      summary: "Find user by ID"
      description: "Returns a single user"
      security:
      - passbolt_auth:
        - "write:user"
    put:
      tags: 
      - "User"
      summary: "Update an existing user"
      description: |
        Updates the specified user by setting the values of the parameters passed. Any parameters not provided will be left unchanged.  
          
          This request accepts mostly the same arguments as the `User` creation call.
      operationId: "updateUser"
      security:
      - passbolt_auth:
        - "write:user"
        - "read:user"
    delete:
      operationId: "deleteUser"
      tags: 
      - "User"
      summary: "Deletes a user"
      description: |
        Deletes the user and also drops all the associated permissions.
      security:
        - passbolt_auth:
          - "delete:user"
  
  "/users/{userId}/dry-run":
    delete:
      tags:
      - User
      summary: Checks if a user can be deleted
      description: Useful when you want to check and avoid any side effects of deleting a user.
      security:
        - passbolt_auth:
          - "delete:user"
      
  "/groups.json":
    get:
      description: Returns a list of your groups. The groups are returned sorted alphabetically by their name.
      summary: List all groups
      operationId: "getGroups"
      tags: 
      - "Group"
      security:
      - passbolt_auth:
        - "read:group"
    
    post:
      operationId: "createGroup"
      tags: 
      - "Group"
      summary: Creates a new group.
      description: Creates a new group.
      security:
      - passbolt_auth:
        - "write:group"
    
  "/groups/{groupId}.json":  
    get:
      operationId: "getGroup"
      tags: 
      - "Group"
      summary: "Find group by ID"
      description: "Returns a single group"
      security:
      - passbolt_auth:
        - "write:group"
    put:
      tags: 
      - "Group"
      summary: "Update an existing group"
      description: |
        Updates the specified group by setting the values of the parameters passed. Any parameters not provided will be left unchanged.  
          
          This request accepts mostly the same arguments as the `Group` creation call.
      operationId: "updateGroup"
      security:
      - passbolt_auth:
        - "write:group"
        - "read:group"
    delete:
      operationId: "deleteGroup"
      tags: 
      - "Group"
      summary: "Deletes a group"
      description: |
        Deletes the group and also drops all the associated permissions.
      security:
        - passbolt_auth:
          - "delete:group"
          
  "/share/search-aros.json":
    get:
      tags: 
      - "Share"
      summary: Get a list of Access Resource Objects or AROs
      description: Get a list of all the users/groups with whom an item can be shared
  "/share/simulate/resource/{resourceId}.json":
    post:
      tags: 
      - "Share"
      summary: "Simulates sharing a password."
      description: |
        Simulates sharing a resource with a user and/or group. Usefull for avoiding any side effects and checking the possible errors.
      operationId: "simulateShare"
      security:
      - passbolt_auth:
        - "share:resource"
        
  "/share/resource/{resourceId}.json":
    put:
      tags: 
      - "Share"
      summary: "Share a password"
      description: |
        Shares a password.
      operationId: "shareResource"
      security:
      - passbolt_auth:
        - "share:resource"

  "/permissions/resource/{resourceId}.json":
    get:
      tags:
      - "Permission"
      summary: "TODO Summary"
      description: "TODO Description"
  "/favorites/resource/{resourceId}.json":
    post:
      tags:
      - "Favorite"
      summary: "Add Password to favourites"
      description: "Add the given password to list of favourites"
  "/favorites/{favoriteId}.json":
    delete:
      tags:
      - "Favorite"
      summary: Delete a favorite entry
      description: Remove a password from the list of favorites
  "/comments/resource/{resourceId}.json":
    get:
      tags:
      - Comment
      summary: List all comments on the record
      description: List all comments on an entity of `model` type and identified by `modelId`
      security:
      - passbolt_auth:
        - "read:comment"
    
    post:
      tags:
      - Comment
      summary: Add a comment to a resource
      description: Add a comment to a resource
      security:
      - passbolt_auth:
        - "write:comment"
               
  "/comments/{commentId}.json":
    put:
      tags:
      - Comment
      summary: Update a comment
      description: Update a comment
      security:
      - passbolt_auth:
        - "write:comment"
    
    delete:
      tags:
      - Comment
      summary: Delete a comment
      description: Delete a comment
      security:
      - passbolt_auth:
        - "write:comment"
      
  "/gpgkeys.json":
    get:
      tags:
      - GPG Key
      summary: List all the GPG kyes
      description: Fetches a list of all your GPG keys
      security:
      - passbolt_auth:
        - "read:gpgkey"
                  
  "/gpgkeys/{keyId}.json":
    get:
      tags:
      - GPG Key
      summary: Find GPG key by ID
      description: Returns a single GPG key
      security:
      - passbolt_auth:
        - "read:gpgkey"
        
  "/secrets/resource/{resourceId}.json":
    get:
      tags:
      - Secret
      summary: Get password for a given resource.
      description: Will return the secret password encoded with user's GPG key. This will need to be decrypted on the client end to get the actual password string.
      security:
      - passbolt_auth:
        - "read:secret"
  
  "/settings.json":
    get:
      tags:
      - Settings
      summary: List the user level settings
      security:
      - passbolt_auth:
        - "read:settings"
                        
  "/roles.json":
    get:
      tags:
      - Role
      summary: List the available user roles
      security:
      - passbolt_auth:
        - "read:role"
        
  "/healthcheck.json":
    get:
      tags:
      - Health Check
      summary: Perform a healthcheck
      description: Return server status report
      security:
      - passbolt_auth:
        - "read:healthcheck"
      
  "/healthcheck/status.json":
    get:
      tags:
      - Health Check
      summary: Get the healthcheck status
      description: Return server status
      security:
      - passbolt_auth:
        - "read:healthcheck"              
    
securityDefinitions:
  passbolt_auth:
    type: "oauth2"
    authorizationUrl: "https://api.passbolt.com/oauth/dialog"
    flow: "implicit"
    scopes:
      write:resource: "modify password in your account"
      read:resource: "read your passwords"
      share:resource: "share your passwords"
      write:user: "modify user in your account"
      read:user: "read your users"
      delete:user: "delete your users"
      read:group: "read your groups"
      write:group: "modifiy your groups"
      delete:group: "delete your groups"
      read:comment: "read your comments"
      write:comment: "write your comments"
      read:gpgkey: "read your gpg keys"
      read:secret: "read your resource secret"
      read:settings: "read your settings"
      read:role: "read your roles"
      read:healthcheck: "read your healthcheck status"